package ftc.evlib.util;

import android.util.Log;

/**
 * This file was made by the electronVolts, FTC team 7393
 * Date Created: 8/26/16
 *
 * Records and logs the time it takes to complete steps in an algorithm
 */
public class StepTimer {
    private final String tag;
    private final int priority;
    private long timer = -1;
    private String message = "";

    /**
     * @param tag      the tag to give to the android logging
     *                 You can search for the tag in the logs to find messages generated by your code
     * @param priority which log level to use
     */
    public StepTimer(String tag, int priority) {
        this.tag = tag;
        this.priority = priority;
    }

    /**
     * reset the timer
     */
    public void start() {
        timer = -1;
    }

    /**
     * Log the previous step (if any) and start a step
     */
    public void step(String message) {
        log();
        timer = System.nanoTime();
        this.message = message;
    }

    /**
     * log the previous step and reset the timer
     */
    public void stop() {
        log();
        timer = -1;
    }

    /**
     * Log the time the step took, along with the message
     */
    private void log() {
        if (timer != -1) {
            Log.println(priority, tag, "TIME: " + message + ": " + String.valueOf((System.nanoTime() - timer) / 1000000.0) + " ms");
        }
    }
}
